name: Python Discord Bot CI

on:
  push:
    branches: ["master"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install PM2
        run: npm install pm2 -g
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt
          
      - name: Create directories for credentials
        run: mkdir -p src/constants

      - name: Decode Google Sheets credentials
        run: echo "${{secrets.GOOGLE_SHEETS_CREDENTIALS_BASE64}}" | base64 --decode > src/constants/token.json
      
      - name: Set environment variables
        run: echo "${{secrets.ENV_VARIABLES}}" | base64 --decode > .env

      - name: Prepare deployment package
        run: tar czf discord_bot.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: discord_bot
          path: discord_bot.tar.gz

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: discord_bot

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "discord_bot.tar.gz"
          target: "~/discord_bot.tar.gz"

      - name: Deploy and restart PM2 on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            mkdir -p discord_bot
            tar xzf ~/discord_bot.tar.gz -C ~/discord_bot
            cd discord_bot
            touch .env
            echo BOT_TOKEN=${{secrets.BOT_TOKEN}} >> .env
            echo GOOGLE_SHEETS_CREDENTIALS_PATH=${{secrets.GOOGLE_SHEETS_CREDENTIALS_PATH}} >> .env
            echo SHEET_NAME=${{secrets.SHEET_NAME}} >> .env
            echo WORKSHEET_NAME=${{secrets.WORKSHEET_NAME}} >> .env
            cat .env
            mkdir -p src/constants
            touch src/constants/token.json
            echo ${{secrets.GOOGLE_SHEETS_CREDENTIALS_BASE64}} | base64 --decode > src/constants/token.json
            pwd
            