name: Python Discord Bot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests available"

    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS_PATH: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_PATH }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
      run: |
        python app.py
