name: Python Discord Bot CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          npm install pm2 -g
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Decode Google Sheets credentials
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS_BASE64 }}" | base64 --decode > src/constants/token.json
          
      - name: Prepare deployment package
        run: |
          tar czf discord_bot.tar.gz *
      
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: 129.154.225.47
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "discord_bot.tar.gz"
          target: "/home/ubuntu/discord_bot/"

      - name: Deploy and restart PM2 on VPS
        uses: appleboy/ssh-action@v0.1.0
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_SHEETS_CREDENTIALS_PATH: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_PATH }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
        with:
          host: 129.154.225.47
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/discord_bot/
            tar xzf discord_bot.tar.gz
            pm2 restart reminder-bot || pm2 start app.py --name "reminder-bot"
