name: Python Discord Bot CI

on:
  push:
    branches: ["master"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install PM2
        run: npm install pm2 -g
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt
          
      - name: Create directories for credentials
        run: mkdir -p src/constants

      - name: Decode Google Sheets credentials
        shell: bash
        run: |
          echo ${{secrets.GOOGLE_SHEETS_CREDENTIALS_BASE64}} | base64 --decode > src/constants/token.json
      
      - name: Set environment variables
        shell: bash
        run: |
          echo ${{secrets.ENV_VARIABLES}} | base64 --decode > .env

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "."
          target: "~/discord_bot"

      - name: Deploy and restart PM2 on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ~/discord_bot
            rm .env
            touch .env
            echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            echo GOOGLE_SHEETS_CREDENTIALS_PATH=src/constants/token.json >> .env
            echo SHEET_NAME=${{ secrets.SHEET_NAME }} >> .env
            echo WORKSHEET_NAME=${{ secrets.WORKSHEET_NAME }} >> .env
            mkdir -p src/constants
            echo ${{secrets.GOOGLE_SHEETS_CREDENTIALS_BASE64}} | base64 --decode > src/constants/token.json
            pm2 start app.py --name "reminder-bot" || pm2 restart reminder-bot
            pm2 save
